export const ROUTES = {
  home: "/",
  /** Selector jugador / club, post-login si hay membresía de club. */
  chooseMode: "/elegir",
  auth: {
    login: "/ingresar",
    register: "/registro",
    checkEmail: "/revisar-correo",
    verifyEmail: "/verificar-email",
  },
  legal: {
    privacy: "/privacidad",
    terms: "/terminos",
  },
  player: {
    root: "/",
    home: "/",
    tournaments: "/torneos",
    tournamentDetail: (id: string) => `/torneos/${id}`,
    ranking: "/ranking",
    history: "/historial",
    profile: "/perfil",
    clubs: "/clubes",
    match: (id: string) => `/partidos/${id}`,
  },
  club: {
    root: "/club",
    dashboard: "/club",
    tournaments: "/club/torneos",
    tournamentNew: "/club/torneos/nuevo",
    tournamentDetail: (id: string) => `/club/torneos/${id}`,
    players: "/club/jugadores",
    clients: "/club/clientes",
    clientDetail: (id: string) => `/club/clientes/${id}`,
    courts: "/club/canchas",
    courtConfig: (id: string) => `/club/canchas/${id}`,
    schedule: "/club/agenda",
    settings: "/club/configuracion",
  },
} as const;
